<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="RoleManage.aspx.cs" Inherits="用户权限角色管理.RoleManager" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h3>角色管理</h3>
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="UserManage.aspx" Target="_self">用户管理</asp:HyperLink>
        <br />
        <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="MenuManage.aspx" Target="_self">菜单管理</asp:HyperLink>
        <panel>
            <h5>角色列表</h5>
            <asp:GridView ID="gvRole" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="gvRole_RowDeleting" OnSelectedIndexChanged="gvRole_SelectedIndexChanged" AutoGenerateSelectButton="True">
            </asp:GridView>
        </panel>
         <panel>
            <h5>编辑角色</h5>
            <asp:Label ID="Label5" runat="server" Text="ID:"></asp:Label>
            <asp:Label ID="lblID" runat="server" Text=""></asp:Label>
            <br />
            <asp:Label ID="Label3" runat="server" Text="角色名："></asp:Label>
            <asp:TextBox ID="TBModRoleName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label4" runat="server" Text="状态："></asp:Label>
            <asp:RadioButton ID="rbModRoleActive" runat="server" GroupName="ModRoleStatus" Text="启用" />
            <asp:RadioButton ID="rbModRoleDisActive" runat="server" GroupName="ModRoleStatus" Text="停用" />
            <br />
             拥有菜单：<asp:CheckBoxList ID="cblModMenus" RepeatDirection="Horizontal" runat="server"></asp:CheckBoxList>
            <br />
            <asp:Button ID="btnMod" runat="server" Text="修改" OnClick="btnMod_Click"/>
        </panel>
        <panel>
            <h5>新增角色</h5>
            <asp:Label ID="Label1" runat="server" Text="角色名："></asp:Label>
            <asp:TextBox ID="tbRoleName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label2" runat="server" Text="状态："></asp:Label>
            <asp:RadioButton ID="rbRoleActive" runat="server" Checked="True" GroupName="RoleStatus" Text="启用" />
            <asp:RadioButton ID="rbRoleDisActive" runat="server" GroupName="RoleStatus" Text="停用" />
            <br />
            <asp:Button ID="btnAdd" runat="server" Text="新增" OnClick="btnAdd_Click" />
        </panel>
    </form>
</body>
</html>
