<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserManage.aspx.cs" Inherits="用户权限角色管理.UserManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h3>用户管理</h3>
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="RoleManage.aspx" Target="_self">角色管理</asp:HyperLink>
        <br />
        <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="MenuManage.aspx" Target="_self">菜单管理</asp:HyperLink>
        <panel>
            <h5>用户列表</h5>
            <asp:GridView ID="gvUser" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="gvUser_RowDeleting" OnSelectedIndexChanged="gvUser_SelectedIndexChanged" AutoGenerateSelectButton="True">
            </asp:GridView>
        </panel>
        <panel>
            <h5>编辑用户</h5>
            <asp:Label ID="Label5" runat="server" Text="ID:"></asp:Label>
            <asp:Label ID="lblID" runat="server" Text=""></asp:Label>
            <br />
            <asp:Label ID="Label3" runat="server" Text="用户名："></asp:Label>
            <asp:TextBox ID="TBModUserName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label6" runat="server" Text="密码："></asp:Label>
            <asp:TextBox ID="TBModUserPwd" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label4" runat="server" Text="状态："></asp:Label>
            <asp:RadioButton ID="rbModUserActive" runat="server" GroupName="ModUserStatus" Text="启用" />
            <asp:RadioButton ID="rbModUserDisActive" runat="server" GroupName="ModUserStatus" Text="停用" />
            <br />
            拥有角色：<asp:CheckBoxList ID="cblModRoles" RepeatDirection="Horizontal" runat="server"></asp:CheckBoxList>
            <br />
            <asp:Button ID="btnMod" runat="server" Text="修改" OnClick="btnMod_Click"/>
        </panel>
        <panel>
            <h5>新增用户</h5>
            <asp:Label ID="Label1" runat="server" Text="用户名："></asp:Label>
            <asp:TextBox ID="tbUserName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label7" runat="server" Text="密码："></asp:Label>
            <asp:TextBox ID="tbUserPwd" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label2" runat="server" Text="状态："></asp:Label>
            <asp:RadioButton ID="rbUserActive" runat="server" Checked="True" GroupName="UserStatus" Text="启用" />
            <asp:RadioButton ID="rbUserDisActive" runat="server" GroupName="UserStatus" Text="停用" />
            <br />
            <asp:Button ID="btnAdd" runat="server" Text="新增" OnClick="btnAdd_Click" />
        </panel>
    </form>
</body>
</html>
